
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 06 11:05:47 PYST 2016
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 14;
  public static final int LPAREN = 27;
  public static final int INT = 6;
  public static final int FOR = 9;
  public static final int RPAREN = 28;
  public static final int AND = 23;
  public static final int IGUAL = 21;
  public static final int OR = 24;
  public static final int BOOL = 5;
  public static final int DIV = 15;
  public static final int NUM = 34;
  public static final int MAIN = 2;
  public static final int IF = 25;
  public static final int ID = 35;
  public static final int EOF = 0;
  public static final int ASIG = 16;
  public static final int AMP = 33;
  public static final int RETURN = 4;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int DIF = 22;
  public static final int MENOS = 13;
  public static final int MENOR = 17;
  public static final int VOID = 3;
  public static final int LLI = 29;
  public static final int MENIG = 18;
  public static final int MAYOR = 19;
  public static final int LLD = 30;
  public static final int PUTS = 7;
  public static final int ELSE = 26;
  public static final int MAYIG = 20;
  public static final int WHILE = 11;
  public static final int GETS = 8;
  public static final int FALSE = 36;
  public static final int DO = 10;
  public static final int PYC = 31;
  public static final int MAS = 12;
}

