
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 05 18:23:07 PYST 2016
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 15;
  public static final int LPAREN = 28;
  public static final int INT = 6;
  public static final int FOR = 10;
  public static final int RPAREN = 29;
  public static final int AND = 24;
  public static final int IGUAL = 22;
  public static final int OR = 25;
  public static final int BOOL = 5;
  public static final int DIV = 16;
  public static final int NUM = 35;
  public static final int MAIN = 2;
  public static final int IF = 26;
  public static final int ID = 36;
  public static final int EOF = 0;
  public static final int ASIG = 17;
  public static final int AMP = 34;
  public static final int RETURN = 4;
  public static final int TRUE = 38;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int DIF = 23;
  public static final int MENOS = 14;
  public static final int MENOR = 18;
  public static final int VOID = 3;
  public static final int LLI = 30;
  public static final int MENIG = 19;
  public static final int MAYOR = 20;
  public static final int LLD = 31;
  public static final int PUTS = 8;
  public static final int ELSE = 27;
  public static final int MAYIG = 21;
  public static final int POINT = 7;
  public static final int WHILE = 12;
  public static final int GETS = 9;
  public static final int FALSE = 37;
  public static final int DO = 11;
  public static final int PYC = 32;
  public static final int MAS = 13;
}

